[DownloadFiles]
DownloadURL=https://dl.google.com/dl/earth/client/advanced/current/googleearthprowin-7.3.7.exe
DownloadName=Google Earth Pro (x32)
DownloadFilename=googleearthprowin-7.3.7.exe
DownloadSHA256=80116b7dec305a9b0a62b49b3865c597485213fb3c3391c6dcefb6b5cbf5c8c8
AdditionalInstallSize=191500
AdvancedExtract1To=App\tmp32\
AdvancedExtract1Filter=*
;Download2URL=https://dl.google.com/dl/earth/client/advanced/current/googleearthprowin-7.3.7-x64.exe
;Download2Name=Google Earth Pro (x64)
;Download2Filename=googleearthprowin-7.3.7-x64.exe
;DownloadSHA256=d58f4db230805387ecad5bedff5e373a803b410ef1f995a6660e92ef9d7f429e
;Download2AdvancedExtract1To=App\tmp64\
;Download2AdvancedExtract1Filter=*
